### ISSUE TITLE
즐겨찾기 기능 만들기

### ISSUE THREAD

**Issue by MinZombie** [MinZombie/PhotosMVVM#3]
## TODO
- [x] 이미지에 즐겨찾기 버튼 만들기
- [x] 즐겨찾기 한 사진들만 볼 수 있는 화면 만들기
- [x] 즐겨찾기 하거나 해제 했을 때 다른 화면과 동기화
